services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    ports:
      - "54321:1433"
    environment:
      SA_PASSWORD: "Korniszon12!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - sqlserver_network

volumes:
  sqlserver_data:
    driver: local

networks:
  sqlserver_network:
    driver: bridge
